version: "3.2"

services:
    #nightwatch:
    #    image: node

    selenium-hub:
        image: selenium/hub:3.7.1
        ports:
            - "4444:4444"
        expose:
            - "4444"
        networks:
            network_hub:
                aliases:
                    - "hub"

    chrome:
        image: selenium/node-chrome:3.7.1
        links:
            - selenium-hub:hub
        volumes:
            - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
        networks:
            network_hub:

    firefox:
        image: selenium/node-firefox:3.7.1
        networks:
            network_hub:

networks:
    network_hub:
        driver: bridge
